services:  
  client:
    build: .
    ports:
      - "5000:5000"
    container_name: node-api
    restart: always
    depends_on: 
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/${MONGO_INITDB_DATBASE}
    networks:
      - app-network


  mongo:
    image: mongo:4
    restart: always
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATBASE=${MONGO_INITDB_DATBASE}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  
networks:
  app-network:
    driver: bridge
        